# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ea7bc673a3b8bf841f4e5c531db97eb1397ac208ca80d2ed62326c0c1416ac6af986bc29b2ecf61cf3c87f784d3d38232b15a34fc91cd1803af39ca90417c59

test:
  secret_key_base: ff4352f7c2feb441f9ae70a41830f114a5949d6fdba351d2069b4cf882dbe0cfd84f4dfebf545cf34939dc8da7b7acba0f0fac230ccc70e16119c98ac6b777ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
